# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# yaml file for develop/master branches build
trigger:
  branches:
    exclude:
    - main
    include:
    - feature/*

pr: none 

pool: 'Azure Pipelines'
variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: "Release"
  - name : NugetSecurityAnalysisWarningLevel
    value : none
  - group: "reddog-dev"

stages:
- stage: BuildStage
  displayName: Build
  jobs:
  # Main build job 
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: runtime
        version: '3.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
      displayName: 'Install dotnet core'
  
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        # feedsToUse: 'config'
        # nugetConfigPath: 'nuget.config'
        projects: '**/*.csproj'
      displayName: 'Dotnet Restore'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        feedsToUse: 'config'
      displayName: 'Build the solution'
      
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        repository: $(accountingServiceImage)
        Dockerfile: 'Dockerfile'
        tags: $(Build.BuildId)    